name: MacOS C++ Build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup C++ Environment
      run: |
        brew install gcc

    - name: Compile Project
      run: |
        make
