name: MacOS Memory Leak Check

on: [push, pull_request]

jobs:
  memory-leak-check:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Project
      run: |
        make

    - name: Check for Memory Leaks
      run: |
        leaks --atExit -- ./webserv
